import 'dart:io';
import 'dart:convert';

void main() async {
  final completeJsonPath = 'assets/data/ap_police_hierarchy_complete.json';
  final firJsonPath = 'assets/data/ap_police_hierarchy_fir.json';
  final outputPath = 'lib/data/station_data_constants.dart';

  print('Reading JSON files...');
  
  final completeFile = File(completeJsonPath);
  final firFile = File(firJsonPath);

  if (!await completeFile.exists()) {
    print('Error: $completeJsonPath not found');
    exit(1);
  }
  if (!await firFile.exists()) {
    print('Error: $firJsonPath not found');
    exit(1);
  }

  final completeJson = json.decode(await completeFile.readAsString());
  final firJson = json.decode(await firFile.readAsString());

  final buffer = StringBuffer();
  buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
  buffer.writeln('// Generated by tool/generate_station_data.dart');
  buffer.writeln();
  
  // Write Complete Hierarchy
  buffer.writeln('const Map<String, dynamic> kPoliceHierarchyComplete = ${jsonEncode(completeJson)};');
  buffer.writeln();

  // Write FIR Hierarchy
  buffer.writeln('const Map<String, dynamic> kPoliceHierarchyFir = ${jsonEncode(firJson)};');

  final outputFile = File(outputPath);
  await outputFile.parent.create(recursive: true);
  await outputFile.writeAsString(buffer.toString());
  
  print('Successfully generated $outputPath');
}
