#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Add case detail screen localization keys to .arb files"""

import json
import os

# Path to l10n directory
l10n_dir = 'frontend/lib/l10n'

# English translations with descriptions
en_translations = {
    'firDetails': ('FIR Details', 'Case Detail Screen tab title'),
    'crimeScene': ('Crime Scene', 'Case Detail Screen tab title'),
    'investigation': ('Investigation', 'Case Detail Screen tab title'),
    'evidence': ('Evidence', 'Case Detail Screen tab title'),
    'finalReport': ('Final Report', 'Case Detail Screen tab title'),
    'editCase': ('Edit Case', 'Button tooltip to edit case'),
    'caseInformation': ('Case Information', 'Section header for case info'),
    'firNumber': ('FIR Number', 'Label for FIR number field'),
    'year': ('Year', 'Label for year field'),
    'complaintId': ('Complaint ID', 'Label for complaint ID field'),
    'firDate': ('FIR Date', 'Label for FIR date field'),
    'firFiledAt': ('FIR Filed At', 'Label for FIR filing timestamp'),
    'policeStation': ('Police Station', 'Label for police station field'),
    'occurrenceOfOffence': ('Occurrence of Offence', 'Section header for incident details'),
    'dayOfOccurrence': ('Day of Occurrence', 'Label for incident date field'),
    'from': ('From', 'Label for start date/time'),
    'to': ('To', 'Label for end date/time'),
    'timePeriod': ('Time Period', 'Label for time period field'),
    'priorToDateTimeDetails': ('Prior to Date/Time Details', 'Label for prior date/time'),
    'beatNumber': ('Beat Number', 'Label for beat number field'),
    'streetVillage': ('Street / Village', 'Label for street/village field'),
    'areaMandal': ('Area / Mandal', 'Label for area/mandal field'),
    'cityDistrict': ('City / District', 'Label for city/district field'),
    'pin': ('PIN', 'Label for PIN code field'),
    'latitude': ('Latitude', 'Label for latitude field'),
    'longitude': ('Longitude', 'Label for longitude field'),
    'distanceFromPS': ('Distance from PS', 'Label for distance from police station'),
    'directionFromPS': ('Direction from PS', 'Label for direction from police station'),
    'outsideJurisdiction': ('Outside Jurisdiction', 'Label for jurisdiction checkbox'),
    'informationReceivedAtPS': ('Information Received at PS', 'Section header'),
    'dateTimeReceived': ('Date & Time Received', 'Label for date and time info'),
    'gdEntryNo': ('GD Entry No.', 'Label for general diary entry number'),
    'typeOfInformation': ('Type of Information', 'Label for information type'),
    'complainantInformantDetails': ('Complainant / Informant Details', 'Section header'),
    'name': ('Name', 'Label for name field'),
    'fatherHusbandName': ('Father/Husband Name', 'Label for father/husband name'),
    'dob': ('Date of Birth', 'Label for DOB field'),
    'nationality': ('Nationality', 'Label for nationality field'),
    'caste': ('Caste', 'Label for caste field'),
    'occupation': ('Occupation', 'Label for occupation field'),
    'mobileNumber': ('Mobile Number', 'Label for mobile number field'),
    'address': ('Address', 'Label for address field'),
    'passportNo': ('Passport No.', 'Label for passport number'),
    'passportPlaceOfIssue': ('Passport Place of Issue', 'Label for passport place'),
    'passportDateOfIssue': ('Passport Date of Issue', 'Label for passport date'),
    'victimDetails': ('Victim Details', 'Section header'),
    'religion': ('Religion', 'Label for religion field'),
    'complainantAlsoVictim': ('Complainant is also the Victim', 'Label for checkbox'),
    'accusedDetails': ('Accused Details', 'Section header'),
    'accused': ('Accused', 'Label for accused person'),
    'propertiesDelayInquest': ('Properties / Delay / Inquest', 'Section header'),
    'propertiesInvolved': ('Properties Involved', 'Label for properties field'),
    'totalValueINR': ('Total Value (Rs.)', 'Label for total property value'),
    'delayInReporting': ('Delay in Reporting', 'Label for reporting delay field'),
    'inquestReportCaseNo': ('Inquest Report Case No.', 'Label for inquest case number'),
    'actsStatement': ('Acts & Statement', 'Section header'),
    'actsAndSectionsInvolved': ('Acts & Sections Involved:', 'Label for acts/sections'),
    'complaintStatement': ('Complaint / Statement:', 'Label for complaint statement'),
    'briefIncidentDetails': ('Brief Incident Details:', 'Label for incident details'),
    'actionTakenAndConfirmation': ('Action Taken & Confirmation', 'Section header'),
    'actionTaken': ('Action Taken', 'Label for action taken field'),
    'investigatingOfficer': ('Investigating Officer', 'Label for IO name'),
    'rank': ('Rank', 'Label for officer rank'),
    'dispatchToCourtDateTime': ('Dispatch to Court Date & Time', 'Label for court dispatch'),
    'dispatchingOfficer': ('Dispatching Officer', 'Label for dispatching officer'),
    'dispatchingOfficerRank': ('Dispatching Officer Rank', 'Label for dispatcher rank'),
    'firReadAndAdmittedCorrect': ('FIR Read and Admitted Correct', 'Label for FIR admission'),
    'copyGivenFreeOfCost': ('Copy Given Free of Cost', 'Label for copy provision'),
    'roacRecorded': ('ROAC Recorded', 'Label for ROAC checkbox'),
    'signatureThumbImpression': ('Signature / Thumb Impression', 'Label for signature'),
    'yes': ('Yes', 'Boolean field option'),
    'no': ('No', 'Boolean field option'),
    'crimeScenes': ('Crime Scenes', 'Section title'),
    'addScene': ('Add Scene', 'Button tooltip'),
    'noCrimeScenesLinked': ('No crime scenes linked to this case yet.', 'Empty state message'),
    'unknownType': ('Unknown Type', 'Default label for unknown crime type'),
    'deleteScene': ('Delete Scene', 'Dialog title'),
    'areSureDeleteScene': ('Are you sure you want to delete this scene?', 'Confirmation message'),
    'place': ('Place', 'Label for place description'),
    'physicalEvidence': ('Physical Evidence', 'Label for physical evidence'),
    'recorded': ('Recorded:', 'Label for timestamp'),
    'captureCrimeSceneEvidence': ('Capture Crime Scene Evidence', 'Section title'),
    'photo': ('Photo', 'Button label'),
    'video': ('Video', 'Button label'),
    'upload': ('Upload', 'Button label'),
    'evidenceFiles': ('Evidence Files', 'Label for file count'),
    'analyzeSceneWithAI': ('Analyze Scene with AI', 'Button label'),
    'analyzing': ('Analyzing...', 'Status text'),
    'aiSceneAnalysis': ('AI Scene Analysis', 'Title'),
    'crimeSceneAnalysisReports': ('Crime Scene Analysis Reports', 'Section title'),
    'noAnalysisReportsFound': ('No analysis reports found.', 'Empty state message'),
    'caseJournalIOsDiary': ('Case Journal (IO\'s Diary)', 'Section title'),
    'noJournalEntriesYet': ('No journal entries yet for this case.', 'Empty state message'),
    'crimeSceneCaptures': ('Crime Scene Captures', 'Section title'),
    'fromInvestigationDiary': ('From Investigation Diary', 'Section title'),
    'fromPetitions': ('From Petitions', 'Section title'),
    'forensicAnalysisReports': ('Forensic Analysis Reports', 'Section title'),
    'noEvidenceDocumentsFound': ('No evidence documents found', 'Empty state message'),
    'attachedDocumentsWillAppearHere': ('Attached documents from case journal, petitions and crime scene captures will appear here.', 'Description text'),
    'noDocumentsAttachedJournal': ('No documents attached to investigation diary yet.', 'Empty state message'),
    'noPetitionDocumentsLinked': ('No petition documents linked to this case yet.', 'Empty state message'),
    'finalInvestigationReport': ('Final Investigation Report / Court Document', 'Section title'),
    'generatedOn': ('Generated On:', 'Label'),
    'noFinalReportAttached': ('No final investigation report attached to this case yet.', 'Empty state message'),
    'onceSomeoneGeneratesReport': ('Once the Investigating Officer generates and confirms an AI-assisted investigation report from the Case Journal screen, the final PDF will be linked here.', 'Description text'),
    'courtReadyReportGenerated': ('Court-ready investigation report PDF has been generated and attached to this case.', 'Info message'),
    'downloadViewFinalReportPDF': ('Download / View Final Report PDF', 'Button label'),
    'loadingEvidenceFromAllSources': ('Loading evidence from all sources...', 'Loading message'),
    'addCrimeScene': ('Add Crime Scene', 'Dialog title'),
    'editCrimeScene': ('Edit Crime Scene', 'Dialog title'),
    'crimeType': ('Crime Type', 'Label for field'),
    'placeDescription': ('Place Description', 'Label for field'),
    'physicalEvidenceDescription': ('Physical Evidence Description', 'Label for field'),
    'cancel': ('Cancel', 'Button text'),
    'save': ('Save', 'Button text'),
    'crimeSceneAdded': ('Crime scene added', 'Success message'),
    'crimeSceneUpdated': ('Crime scene updated', 'Success message'),
    'errorSavingCrimeScene': ('Error:', 'Error prefix'),
    'delete': ('Delete', 'Button text'),
    'uploadingCapturedEvidence': ('Uploading captured evidence...', 'Status message'),
    'failedUploadEvidence': ('Failed to upload evidence', 'Error message'),
    'geoTaggedPhotoCaptured': ('Geo-tagged photo captured', 'Success message'),
    'geoTaggedVideoCaptured': ('Geo-tagged video captured', 'Success message'),
    'uploadEvidence': ('Upload Evidence', 'Dialog title'),
    'chooseFileType': ('Choose File Type:', 'Instructions'),
    'image': ('Image', 'Option'),
    'document': ('Document', 'Option'),
    'uploadingDocument': ('Uploading document...', 'Status message'),
    'failedUploadDocument': ('Failed to upload document', 'Error message'),
    'documentUploaded': ('Document uploaded', 'Success message'),
    'imageUploaded': ('Image uploaded', 'Success message'),
    'videoUploaded': ('Video uploaded', 'Success message'),
    'errorUploadingFile': ('Error uploading file:', 'Error prefix'),
    'pleaseCapturUploadEvidenceFirst': ('Please capture or upload evidence first', 'Warning message'),
    'sceneAnalysisComplete': ('Scene analysis complete!', 'Success message'),
    'analysisError': ('Analysis error:', 'Error prefix'),
    'downloadEvidence': ('Download Evidence', 'Option'),
    'saveToDeviceDownloads': ('Save to device downloads folder', 'Description'),
    'analyzeWithAI': ('Analyze with AI', 'Option'),
    'getForensicAnalysis': ('Get forensic analysis', 'Description'),
    'downloadReport': ('Download Report', 'Button tooltip'),
    'deleteReport': ('Delete Report', 'Button tooltip'),
    'deleteReportConfirmation': ('Are you sure you want to delete this analysis report? This cannot be undone.', 'Confirmation message'),
    'reportDeleted': ('Report deleted', 'Success message'),
    'errorDeletingReport': ('Error deleting report:', 'Error prefix'),
    'generatingPDF': ('Generating PDF...', 'Status message'),
    'errorDownloadingPDF': ('Error downloading PDF:', 'Error prefix'),
    'analyzedOn': ('Analyzed On', 'Label'),
    'identifiedElements': ('Identified Elements:', 'Title'),
    'sceneNarrative': ('Scene Narrative:', 'Title'),
    'caseFileSummary': ('Case File Summary:', 'Title'),
    'filedOn': ('Filed On:', 'Label'),
    'accessViaFileManager': ('Access via File Manager → Dharma → Evidence', 'Instructions'),
    'evidenceDownloaded': ('Evidence downloaded!', 'Success message'),
    'savedTo': ('Saved to:', 'Label'),
    'downloadFailed': ('Download failed:', 'Error prefix'),
    'analysisComplete': ('Analysis complete!', 'Success message'),
    'analysisErrorEvidence': ('Error analyzing evidence:', 'Error prefix'),
    'evidenceRemoved': ('Evidence removed', 'Success message'),
}

# Telugu translations
te_translations = {
    'firDetails': 'FIR వివరాలు',
    'crimeScene': 'నేర దృశ్యం',
    'investigation': 'విచారణ',
    'evidence': 'సాక్ష్యం',
    'finalReport': 'చివరి నివేదిక',
    'editCase': 'కేసును సవరించండి',
    'caseInformation': 'కేసు సమాచారం',
    'firNumber': 'FIR సంఖ్య',
    'year': 'సంవత్సరం',
    'complaintId': 'ఫిర్యాదు ID',
    'firDate': 'FIR తేదీ',
    'firFiledAt': 'FIR ఫైల్ చేసిన సమయం',
    'policeStation': 'పోలీస్ స్టేషన్',
    'occurrenceOfOffence': 'నేర సంభవం',
    'dayOfOccurrence': 'సంభవ తేదీ',
    'from': 'నుండి',
    'to': 'వరకు',
    'timePeriod': 'సమయ కాలం',
    'priorToDateTimeDetails': 'ముందు నుండి తేదీ/సమయ వివరాలు',
    'beatNumber': 'బీట్ సంఖ్య',
    'streetVillage': 'వీధి / గ్రామం',
    'areaMandal': 'ప్రాంతం / మండలం',
    'cityDistrict': 'నగరం / జిల్లా',
    'pin': 'పిన్',
    'latitude': 'అక్షాంశం',
    'longitude': 'రేఖాంశం',
    'distanceFromPS': 'పోలీస్ స్టేషన్ నుండి దూరం',
    'directionFromPS': 'పోలీస్ స్టేషన్ నుండి దిశ',
    'outsideJurisdiction': 'అధికార పరిధిలో ఉండదు',
    'informationReceivedAtPS': 'పోలీస్ స్టేషన్‌లో పొందిన సమాచారం',
    'dateTimeReceived': 'పొందిన తేదీ & సమయం',
    'gdEntryNo': 'GD ఎంట్రీ నం.',
    'typeOfInformation': 'సమాచారం రకం',
    'complainantInformantDetails': 'ఫిర్యాదుదారు / సమాచారదారు వివరాలు',
    'name': 'పేరు',
    'fatherHusbandName': 'తండ్రి/భర్త పేరు',
    'dob': 'జన్మ తేదీ',
    'nationality': 'జాతీయత',
    'caste': 'జాతి',
    'occupation': 'వృత్తి',
    'mobileNumber': 'మోబైల్ సంఖ్య',
    'address': 'చిరునామా',
    'passportNo': 'పాస్‌పోర్ట్ నం.',
    'passportPlaceOfIssue': 'పాస్‌పోర్ట్ జారీ స్థానం',
    'passportDateOfIssue': 'పాస్‌పోర్ట్ జారీ తేదీ',
    'victimDetails': 'బాధితుడి వివరాలు',
    'religion': 'మతం',
    'complainantAlsoVictim': 'ఫిర్యాదుదారు కూడా బాధితుడు',
    'accusedDetails': 'ప్రతిబద్ధుల వివరాలు',
    'accused': 'ప్రతిబద్ధుడు',
    'propertiesDelayInquest': 'ఆస్తులు / ఆలస్యం / విచారణ',
    'propertiesInvolved': 'సంబంధిత ఆస్తులు',
    'totalValueINR': 'మొత్తం విలువ (రూ.)',
    'delayInReporting': 'నివేదనలో ఆలస్యం',
    'inquestReportCaseNo': 'విచారణ నివేదిక / U.D. కేసు నం.',
    'actsStatement': 'చట్టాలు & ప్రకటన',
    'actsAndSectionsInvolved': 'చట్టాలు & సెక్షన్లు:',
    'complaintStatement': 'ఫిర్యాదు / ఫిర్యాదుదారు ప్రకటన:',
    'briefIncidentDetails': 'సంక్షిప్త ఘటన వివరాలు:',
    'actionTakenAndConfirmation': 'చేసిన చర్య & నిర్ధారణ',
    'actionTaken': 'చేసిన చర్య',
    'investigatingOfficer': 'విచారణ అధికారి',
    'rank': 'హోదా',
    'dispatchToCourtDateTime': 'కోర్టుకు పంపిన తేదీ & సమయం',
    'dispatchingOfficer': 'పంపిన అధికారి',
    'dispatchingOfficerRank': 'పంపిన అధికారి హోదా',
    'firReadAndAdmittedCorrect': 'FIR చదువబడింది మరియు సరిగా కీకర్లు చేసుకున్నారు',
    'copyGivenFreeOfCost': 'FIR కాపీ ఉచితంగా ఇవ్వబడింది',
    'roacRecorded': 'ROAC నమోదు చేయబడింది',
    'signatureThumbImpression': 'సంతకం / బొటనవేలి ముద్ర',
    'yes': 'అవును',
    'no': 'కాదు',
    'crimeScenes': 'నేర దృశ్యాలు',
    'addScene': 'దృశ్యం జోడించండి',
    'noCrimeScenesLinked': 'ఈ కేసుకు ఇంకా నేర దృశ్యాలు లింక్ చేయబడలేదు.',
    'unknownType': 'తెలియని రకం',
    'deleteScene': 'దృశ్యం తొలగించండి',
    'areSureDeleteScene': 'మీరు ఈ దృశ్యం తొలగించాలని చేస్తున్నారా?',
    'place': 'స్థానం',
    'physicalEvidence': 'భౌతిక సాక్ష్యం',
    'recorded': 'నమోదు చేయబడింది:',
    'captureCrimeSceneEvidence': 'నేర దృశ్య సాక్ష్యం సంగ్రహించండి',
    'photo': 'ఫోటో',
    'video': 'వీడియో',
    'upload': 'అప్‌లోడ్',
    'evidenceFiles': 'సాక్ష్య ఫైల్‌లు',
    'analyzeSceneWithAI': 'నేర దృశ్యం AI తో విశ్లేషించండి',
    'analyzing': 'విశ్లేషించుచున్నది...',
    'aiSceneAnalysis': 'AI నేర దృశ్య విశ్లేషణ',
    'crimeSceneAnalysisReports': 'నేర దృశ్య విశ్లేషణ నివేదికలు',
    'noAnalysisReportsFound': 'విశ్లేషణ నివేదికలు కనుగొనబడలేదు.',
    'caseJournalIOsDiary': 'కేసు జర్నల్ (IO యొక్క డయరీ)',
    'noJournalEntriesYet': 'ఈ కేసుకు ఇంకా జర్నల్ ఎంట్రీలు లేవు.',
    'crimeSceneCaptures': 'నేర దృశ్య సంగ్రహణలు',
    'fromInvestigationDiary': 'విచారణ డయరీ నుండి',
    'fromPetitions': 'పిటిషన్ల నుండి',
    'forensicAnalysisReports': 'ఫోరెన్సిక్ విశ్లేషణ నివేదికలు',
    'noEvidenceDocumentsFound': 'సాక్ష్య పత్రాలు కనుగొనబడలేదు',
    'attachedDocumentsWillAppearHere': 'కేసు జర్నల్, పిటిషన్‌లు మరియు నేర దృశ్య సంగ్రహణల నుండి జత చేసిన పత్రాలు ఇక్కడ కనిపిస్తాయి.',
    'noDocumentsAttachedJournal': 'విచారణ డయరీలో ఇంకా పత్రాలు జత చేయబడలేదు.',
    'noPetitionDocumentsLinked': 'ఈ కేసుకు ఇంకా పిటిషన్ పత్రాలు లింక్ చేయబడలేదు.',
    'finalInvestigationReport': 'చివరి విచారణ నివేదిక / కోర్టు పత్రం',
    'generatedOn': 'రూపొందించిన తేదీ:',
    'noFinalReportAttached': 'ఈ కేసుకు చివరి విచారణ నివేదిక జత చేయబడలేదు.',
    'onceSomeoneGeneratesReport': 'విచారణ అధికారి కేసు జర్నల్ స్క్రీన్ నుండి AI సహాయక విచారణ నివేదికను రూపొందించి నిర్ధారించిన తర్వాత, చివరి PDF ఇక్కడ లింక్ చేయబడుతుంది.',
    'courtReadyReportGenerated': 'కోర్టుకు సిద్ధ విచారణ నివేదిక PDF రూపొందించబడింది మరియు ఈ కేసుకు జత చేయబడింది.',
    'downloadViewFinalReportPDF': 'చివరి నివేదిక PDFను డౌన్‌లోడ్ / చూడండి',
    'loadingEvidenceFromAllSources': 'అన్ని మూలాల నుండి సాక్ష్యం లోడ్ చేయుచున్నది...',
    'addCrimeScene': 'నేర దృశ్యం జోడించండి',
    'editCrimeScene': 'నేర దృశ్యం సవరించండి',
    'crimeType': 'నేర రకం',
    'placeDescription': 'స్థానం వివరణ',
    'physicalEvidenceDescription': 'భౌతిక సాక్ష్యం వివరణ',
    'cancel': 'రద్దు చేయండి',
    'save': 'సంరక్షించండి',
    'crimeSceneAdded': 'నేర దృశ్యం జోడించబడింది',
    'crimeSceneUpdated': 'నేర దృశ్యం నవీకరించబడింది',
    'errorSavingCrimeScene': 'లోపం:',
    'delete': 'తొలగించండి',
    'uploadingCapturedEvidence': 'సంగ్రహించిన సాక్ష్యం అప్‌లోడ్ చేయుచున్నది...',
    'failedUploadEvidence': 'సాక్ష్యం అప్‌లోడ్ చేయడంలో విఫలమైంది',
    'geoTaggedPhotoCaptured': 'జియో-ట్యాగ్ చేసిన ఫోటో సంగ్రహించబడింది',
    'geoTaggedVideoCaptured': 'జియో-ట్యాగ్ చేసిన వీడియో సంగ్రహించబడింది',
    'uploadEvidence': 'సాక్ష్యం అప్‌లోడ్ చేయండు',
    'chooseFileType': 'ఫైల్ రకం ఎంచుకోండి:',
    'image': 'చిత్రం',
    'document': 'పత్రం',
    'uploadingDocument': 'పత్రం అప్‌లోడ్ చేయుచున్నది...',
    'failedUploadDocument': 'పత్రం అప్‌లోడ్ చేయడంలో విఫలమైంది',
    'documentUploaded': 'పత్రం అప్‌లోడ్ చేయబడింది',
    'imageUploaded': 'చిత్రం అప్‌లోడ్ చేయబడింది',
    'videoUploaded': 'వీడియో అప్‌లోడ్ చేయబడింది',
    'errorUploadingFile': 'ఫైల్ అప్‌లోడ్‌లో లోపం:',
    'pleaseCapturUploadEvidenceFirst': 'మొదట సాక్ష్యం సంగ్రహించండి లేదా అప్‌లోడ్ చేయండి',
    'sceneAnalysisComplete': 'నేర దృశ్య విశ్లేషణ పూర్తి!',
    'analysisError': 'విశ్లేషణ లోపం:',
    'downloadEvidence': 'సాక్ష్యం డౌన్‌లోడ్ చేయండు',
    'saveToDeviceDownloads': 'పరికర డౌన్‌లోడ్‌ల ఫోల్డర్‌కు సేవ్ చేయండి',
    'analyzeWithAI': 'AI తో విశ్లేషించండు',
    'getForensicAnalysis': 'ఫోరెన్సిక్ విశ్లేషణ పొందండు',
    'downloadReport': 'నివేదిక డౌన్‌లోడ్ చేయండు',
    'deleteReport': 'నివేదిక తొలగించండు',
    'deleteReportConfirmation': 'మీరు ఈ విశ్లేషణ నివేదిక తొలగించాలని చేస్తున్నారా? ఇది రద్దు చేయలేము.',
    'reportDeleted': 'నివేదిక తొలగించబడింది',
    'errorDeletingReport': 'నివేదిక తొలగించడంలో లోపం:',
    'generatingPDF': 'PDF రూపొందిస్తున్నది...',
    'errorDownloadingPDF': 'PDF డౌన్‌లోడ్‌లో లోపం:',
    'analyzedOn': 'విశ్లేషించిన తేదీ',
    'identifiedElements': 'గుర్తించిన మూలకాలు:',
    'sceneNarrative': 'నేర వర్ణన:',
    'caseFileSummary': 'కేసు ఫైల్ సారాంశం:',
    'filedOn': 'ఫైల్ చేసిన తేదీ:',
    'accessViaFileManager': 'ఫైల్ మేనేజర్ → ధర్మ → సాక్ష్యం ద్వారా యాక్సెస్ చేయండి',
    'evidenceDownloaded': 'సాక్ష్యం డౌన్‌లోడ్ చేయబడింది!',
    'savedTo': 'సేవ్ చేసిన రిజిస్ట్రేషన:',
    'downloadFailed': 'డౌన్‌లోడ్ విఫలమైంది:',
    'analysisComplete': 'విశ్లేషణ పూర్తి!',
    'analysisErrorEvidence': 'సాక్ష్యం విశ్లేషించడంలో లోపం:',
    'evidenceRemoved': 'సాక్ష్యం తొలగించబడింది'
}

def add_to_arb(filepath, translations, descriptions=None):
    """Add translations to .arb file"""
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # Remove closing brace to add new entries
    if '}' in str(data):
        pass  # json.load handles this
    
    # Add each translation
    for key, value in translations.items():
        if key not in data:
            data[key] = value
            if descriptions and key in descriptions:
                data[f'@{key}'] = {'description': descriptions[key]}
    
    # Write back
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return len(translations)

try:
    # Process English file
    en_descs = {k: v[1] for k, v in en_translations.items()}
    en_vals = {k: v[0] for k, v in en_translations.items()}
    
    en_file = os.path.join(l10n_dir, 'app_en.arb')
    en_count = add_to_arb(en_file, en_vals, en_descs)
    print(f"✓ Added {en_count} keys to English file")
    
    # Process Telugu file
    te_file = os.path.join(l10n_dir, 'app_te.arb')
    te_count = add_to_arb(te_file, te_translations)
    print(f"✓ Added {te_count} keys to Telugu file")
    
    print("\nSuccess! Localization files updated.")
    
except Exception as e:
    print(f"Error: {e}")
    import traceback
    traceback.print_exc()
