#!/usr/bin/env python3
import re

# Read the case_detail_screen.dart file
with open('frontend/lib/screens/case_detail_screen.dart', 'r', encoding='utf-8') as f:
    content = f.read()

# Define all string replacements as (old, new, description) tuples
replacements = [
    ("'FIR Details'", "localizations.firDetails", "FIR Details"),
    ("'Crime Scene'", "localizations.crimeScene", "Crime Scene"),
    ("'Investigation'", "localizations.investigation", "Investigation"),
    ("'Evidence'", "localizations.evidence", "Evidence"),
    ("'Final Report'", "localizations.finalReport", "Final Report"),
    ("'Edit Case'", "localizations.editCase", "Edit Case"),
    ("'Case Information'", "localizations.caseInformation", "Case Information"),
    ("'FIR Number'", "localizations.firNumber", "FIR Number"),
    ("'Year'", "localizations.year", "Year"),
    ("'Complaint ID'", "localizations.complaintId", "Complaint ID"),
    ("'FIR Date'", "localizations.firDate", "FIR Date"),
    ("'FIR Filed At'", "localizations.firFiledAt", "FIR Filed At"),
    ("'Police Station'", "localizations.policeStation", "Police Station"),
    ("'Occurrence of Offence'", "localizations.occurrenceOfOffence", "Occurrence of Offence"),
    ("'Day of Occurrence'", "localizations.dayOfOccurrence", "Day of Occurrence"),
    ("'From'", "localizations.from", "From"),
    ("'To'", "localizations.to", "To"),
    ("'Time Period'", "localizations.timePeriod", "Time Period"),
    ("'Prior to Date/Time Details'", "localizations.priorToDateTimeDetails", "Prior to Date/Time Details"),
    ("'Beat Number'", "localizations.beatNumber", "Beat Number"),
    ("'Street / Village'", "localizations.streetVillage", "Street / Village"),
    ("'Area / Mandal'", "localizations.areaMandal", "Area / Mandal"),
    ("'City / District'", "localizations.cityDistrict", "City / District"),
    ("'PIN'", "localizations.pin", "PIN"),
    ("'Latitude'", "localizations.latitude", "Latitude"),
    ("'Longitude'", "localizations.longitude", "Longitude"),
    ("'Distance from PS'", "localizations.distanceFromPS", "Distance from PS"),
    ("'Direction from PS'", "localizations.directionFromPS", "Direction from PS"),
    ("'Outside Jurisdiction'", "localizations.outsideJurisdiction", "Outside Jurisdiction"),
    ("'Information Received at PS'", "localizations.informationReceivedAtPS", "Information Received at PS"),
    ("'Date & Time Received'", "localizations.dateTimeReceived", "Date & Time Received"),
    ("'GD Entry No.'", "localizations.gdEntryNo", "GD Entry No."),
    ("'Type of Information'", "localizations.typeOfInformation", "Type of Information"),
    ("'Complainant / Informant Details'", "localizations.complainantInformantDetails", "Complainant / Informant Details"),
    ("'Name'", "localizations.name", "Name"),
    ("'Father/Husband Name'", "localizations.fatherHusbandName", "Father/Husband Name"),
    ("'Date of Birth'", "localizations.dob", "Date of Birth"),
    ("'Nationality'", "localizations.nationality", "Nationality"),
    ("'Caste'", "localizations.caste", "Caste"),
    ("'Occupation'", "localizations.occupation", "Occupation"),
    ("'Mobile Number'", "localizations.mobileNumber", "Mobile Number"),
    ("'Address'", "localizations.address", "Address"),
    ("'Passport No.'", "localizations.passportNo", "Passport No."),
    ("'Passport Place of Issue'", "localizations.passportPlaceOfIssue", "Passport Place of Issue"),
    ("'Passport Date of Issue'", "localizations.passportDateOfIssue", "Passport Date of Issue"),
    ("'Victim Details'", "localizations.victimDetails", "Victim Details"),
    ("'Religion'", "localizations.religion", "Religion"),
    ("'Complainant is also the Victim'", "localizations.complainantAlsoVictim", "Complainant is also the Victim"),
    ("'Accused Details'", "localizations.accusedDetails", "Accused Details"),
    ("'Accused'", "localizations.accused", "Accused"),
    ("'Properties / Delay / Inquest'", "localizations.propertiesDelayInquest", "Properties / Delay / Inquest"),
    ("'Properties Involved'", "localizations.propertiesInvolved", "Properties Involved"),
    ("'Total Value (Rs.)'", "localizations.totalValueINR", "Total Value (Rs.)"),
    ("'Delay in Reporting'", "localizations.delayInReporting", "Delay in Reporting"),
    ("'Inquest Report Case No.'", "localizations.inquestReportCaseNo", "Inquest Report Case No."),
    ("'Acts & Statement'", "localizations.actsStatement", "Acts & Statement"),
    ("'Acts & Sections Involved:'", "localizations.actsAndSectionsInvolved", "Acts & Sections Involved"),
    ("'Complaint / Statement:'", "localizations.complaintStatement", "Complaint / Statement"),
    ("'Brief Incident Details:'", "localizations.briefIncidentDetails", "Brief Incident Details"),
    ("'Action Taken & Confirmation'", "localizations.actionTakenAndConfirmation", "Action Taken & Confirmation"),
    ("'Action Taken'", "localizations.actionTaken", "Action Taken"),
    ("'Investigating Officer'", "localizations.investigatingOfficer", "Investigating Officer"),
    ("'Rank'", "localizations.rank", "Rank"),
    ("'Dispatch to Court Date & Time'", "localizations.dispatchToCourtDateTime", "Dispatch to Court Date & Time"),
    ("'Dispatching Officer'", "localizations.dispatchingOfficer", "Dispatching Officer"),
    ("'Dispatching Officer Rank'", "localizations.dispatchingOfficerRank", "Dispatching Officer Rank"),
    ("'FIR Read and Admitted Correct'", "localizations.firReadAndAdmittedCorrect", "FIR Read and Admitted Correct"),
    ("'Copy Given Free of Cost'", "localizations.copyGivenFreeOfCost", "Copy Given Free of Cost"),
    ("'ROAC Recorded'", "localizations.roacRecorded", "ROAC Recorded"),
    ("'Signature / Thumb Impression'", "localizations.signatureThumbImpression", "Signature / Thumb Impression"),
    ("'Yes'", "localizations.yes", "Yes"),
    ("'No'", "localizations.no", "No"),
    ("'Crime Scenes'", "localizations.crimeScenes", "Crime Scenes"),
    ("'Add Scene'", "localizations.addScene", "Add Scene"),
    ("'No crime scenes linked to this case yet.'", "localizations.noCrimeScenesLinked", "No crime scenes linked to this case yet."),
    ("'Unknown Type'", "localizations.unknownType", "Unknown Type"),
    ("'Delete Scene'", "localizations.deleteScene", "Delete Scene"),
    ("'Are you sure you want to delete this scene?'", "localizations.areSureDeleteScene", "Are you sure you want to delete this scene?"),
    ("'Place'", "localizations.place", "Place"),
    ("'Physical Evidence'", "localizations.physicalEvidence", "Physical Evidence"),
    ("'Recorded:'", "localizations.recorded", "Recorded"),
    ("'Capture Crime Scene Evidence'", "localizations.captureCrimeSceneEvidence", "Capture Crime Scene Evidence"),
    ("'Photo'", "localizations.photo", "Photo"),
    ("'Video'", "localizations.video", "Video"),
    ("'Upload'", "localizations.upload", "Upload"),
    ("'Evidence Files'", "localizations.evidenceFiles", "Evidence Files"),
    ("'Analyze Scene with AI'", "localizations.analyzeSceneWithAI", "Analyze Scene with AI"),
    ("'Analyzing...'", "localizations.analyzing", "Analyzing"),
    ("'AI Scene Analysis'", "localizations.aiSceneAnalysis", "AI Scene Analysis"),
    ("'Crime Scene Analysis Reports'", "localizations.crimeSceneAnalysisReports", "Crime Scene Analysis Reports"),
    ("'No analysis reports found.'", "localizations.noAnalysisReportsFound", "No analysis reports found"),
    ("'Case Journal (IO\\'s Diary)'", "localizations.caseJournalIOsDiary", "Case Journal (IO's Diary)"),
    ("'No journal entries yet for this case.'", "localizations.noJournalEntriesYet", "No journal entries yet for this case."),
    ("'Crime Scene Captures'", "localizations.crimeSceneCaptures", "Crime Scene Captures"),
    ("'From Investigation Diary'", "localizations.fromInvestigationDiary", "From Investigation Diary"),
    ("'From Petitions'", "localizations.fromPetitions", "From Petitions"),
    ("'Forensic Analysis Reports'", "localizations.forensicAnalysisReports", "Forensic Analysis Reports"),
    ("'No evidence documents found'", "localizations.noEvidenceDocumentsFound", "No evidence documents found"),
    ("'Attached documents from case journal, petitions and crime scene captures will appear here.'", "localizations.attachedDocumentsWillAppearHere", "Attached documents will appear here"),
    ("'No documents attached to investigation diary yet.'", "localizations.noDocumentsAttachedJournal", "No documents attached to investigation diary yet."),
    ("'No petition documents linked to this case yet.'", "localizations.noPetitionDocumentsLinked", "No petition documents linked to this case yet."),
    ("'Final Investigation Report / Court Document'", "localizations.finalInvestigationReport", "Final Investigation Report / Court Document"),
    ("'Generated On:'", "localizations.generatedOn", "Generated On"),
    ("'No final investigation report attached to this case yet.'", "localizations.noFinalReportAttached", "No final investigation report attached to this case yet."),
    ("'Once the Investigating Officer generates and confirms an AI-assisted investigation report from the Case Journal screen, the final PDF will be linked here.'", "localizations.onceSomeoneGeneratesReport", "Once someone generates report"),
    ("'Court-ready investigation report PDF has been generated and attached to this case.'", "localizations.courtReadyReportGenerated", "Court-ready investigation report PDF has been generated and attached to this case."),
    ("'Download / View Final Report PDF'", "localizations.downloadViewFinalReportPDF", "Download / View Final Report PDF"),
    ("'Loading evidence from all sources...'", "localizations.loadingEvidenceFromAllSources", "Loading evidence from all sources"),
    ("'Add Crime Scene'", "localizations.addCrimeScene", "Add Crime Scene"),
    ("'Edit Crime Scene'", "localizations.editCrimeScene", "Edit Crime Scene"),
    ("'Crime Type'", "localizations.crimeType", "Crime Type"),
    ("'Place Description'", "localizations.placeDescription", "Place Description"),
    ("'Physical Evidence Description'", "localizations.physicalEvidenceDescription", "Physical Evidence Description"),
    ("'Cancel'", "localizations.cancel", "Cancel"),
    ("'Save'", "localizations.save", "Save"),
    ("'Crime scene added'", "localizations.crimeSceneAdded", "Crime scene added"),
    ("'Crime scene updated'", "localizations.crimeSceneUpdated", "Crime scene updated"),
    ("'Error:'", "localizations.errorSavingCrimeScene", "Error"),
    ("'Delete'", "localizations.delete", "Delete"),
    ("'Uploading captured evidence...'", "localizations.uploadingCapturedEvidence", "Uploading captured evidence"),
    ("'Failed to upload evidence'", "localizations.failedUploadEvidence", "Failed to upload evidence"),
    ("'Geo-tagged photo captured'", "localizations.geoTaggedPhotoCaptured", "Geo-tagged photo captured"),
    ("'Geo-tagged video captured'", "localizations.geoTaggedVideoCaptured", "Geo-tagged video captured"),
    ("'Upload Evidence'", "localizations.uploadEvidence", "Upload Evidence"),
    ("'Choose File Type:'", "localizations.chooseFileType", "Choose File Type"),
    ("'Image'", "localizations.image", "Image"),
    ("'Document'", "localizations.document", "Document"),
    ("'Uploading document...'", "localizations.uploadingDocument", "Uploading document"),
    ("'Failed to upload document'", "localizations.failedUploadDocument", "Failed to upload document"),
    ("'Document uploaded'", "localizations.documentUploaded", "Document uploaded"),
    ("'Image uploaded'", "localizations.imageUploaded", "Image uploaded"),
    ("'Video uploaded'", "localizations.videoUploaded", "Video uploaded"),
    ("'Error uploading file:'", "localizations.errorUploadingFile", "Error uploading file"),
    ("'Please capture or upload evidence first'", "localizations.pleaseCapturUploadEvidenceFirst", "Please capture or upload evidence first"),
    ("'Scene analysis complete!'", "localizations.sceneAnalysisComplete", "Scene analysis complete"),
    ("'Analysis error:'", "localizations.analysisError", "Analysis error"),
    ("'Download Evidence'", "localizations.downloadEvidence", "Download Evidence"),
    ("'Save to device downloads folder'", "localizations.saveToDeviceDownloads", "Save to device downloads folder"),
    ("'Analyze with AI'", "localizations.analyzeWithAI", "Analyze with AI"),
    ("'Get forensic analysis'", "localizations.getForensicAnalysis", "Get forensic analysis"),
    ("'Download Report'", "localizations.downloadReport", "Download Report"),
    ("'Delete Report'", "localizations.deleteReport", "Delete Report"),
    ("'Are you sure you want to delete this analysis report? This cannot be undone.'", "localizations.deleteReportConfirmation", "Delete report confirmation"),
    ("'Report deleted'", "localizations.reportDeleted", "Report deleted"),
    ("'Error deleting report:'", "localizations.errorDeletingReport", "Error deleting report"),
    ("'Generating PDF...'", "localizations.generatingPDF", "Generating PDF"),
    ("'Error downloading PDF:'", "localizations.errorDownloadingPDF", "Error downloading PDF"),
    ("'Analyzed On'", "localizations.analyzedOn", "Analyzed On"),
    ("'Identified Elements:'", "localizations.identifiedElements", "Identified Elements"),
    ("'Scene Narrative:'", "localizations.sceneNarrative", "Scene Narrative"),
    ("'Case File Summary:'", "localizations.caseFileSummary", "Case File Summary"),
    ("'Filed On:'", "localizations.filedOn", "Filed On"),
    ("'Access via File Manager → Dharma → Evidence'", "localizations.accessViaFileManager", "Access via File Manager → Dharma → Evidence"),
    ("'Evidence downloaded!'", "localizations.evidenceDownloaded", "Evidence downloaded"),
    ("'Saved to:'", "localizations.savedTo", "Saved to"),
    ("'Download failed:'", "localizations.downloadFailed", "Download failed"),
    ("'Analysis complete!'", "localizations.analysisComplete", "Analysis complete"),
    ("'Error analyzing evidence:'", "localizations.analysisErrorEvidence", "Error analyzing evidence"),
    ("'Evidence removed'", "localizations.evidenceRemoved", "Evidence removed"),
]

# Perform replacements
replaced_count = 0
for old, new, description in replacements:
    if old in content:
        content = content.replace(old, new)
        replaced_count += 1
        print(f"✓ Replaced: {description}")
    else:
        print(f"⚠ Not found: {description}")

# Write the modified content back
with open('frontend/lib/screens/case_detail_screen.dart', 'w', encoding='utf-8') as f:
    f.write(content)

print(f"\n✅ Successfully replaced {replaced_count}/{len(replacements)} strings")
print("✅ case_detail_screen.dart has been updated with localization keys!")
